# Generated by Django 4.1.3 on 2022-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('taste', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
